# Generated by Django 5.1.3 on 2024-12-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0007_alter_company_options_alter_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['code']},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='code',
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='max_sentiment_type',
            field=models.CharField(default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='max_sentiment_value',
            field=models.FloatField(default=0.5),
        ),
    ]
