# Generated by Django 5.1.3 on 2024-12-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP', '0002_alter_news_unique_together_news_company_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
