# Generated by Django 5.1.3 on 2024-12-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP', '0003_news_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(default='', max_length=50)),
                ('max_sentiment', models.CharField(default='neutral', max_length=10)),
                ('max_sentiment_value', models.FloatField(default=0.5)),
            ],
            options={
                'ordering': ['company_code'],
            },
        ),
    ]
