version: '3.8'
services:
  datascraper:
    build:
      context: ./services/datascraper
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000", "--app=datascraper"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
  lstm:
    build:
      context: ./services/lstm
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8001", "--app=lstm"]
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3

  nlp:
    build:
      context: ./services/nlp
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8002", "--app=nlp"]
    ports:
      - "8002:8002"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3

  react-app:
    build:
      context: ./reactapp
      dockerfile: Dockerfile
    command: [ "serve", "-s", "build" ]
    ports:
      - "3000:3000"
    volumes:
      - ./reactapp/src:/app/src
      - ./reactapp/package.json:/app/package.json
    environment:     #better performances, debuging disabled
      - NODE_ENV=production