# Generated by Django 5.1.3 on 2024-12-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.CharField(max_length=5000)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('title', 'date')},
            },
        ),
    ]
