# Generated by Django 4.1 on 2024-11-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0003_dayentryasstring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayentryasstring',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='dayentry',
            unique_together={('company_code', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dayentryasstring',
            unique_together={('company_code', 'date')},
        ),
    ]
