# Generated by Django 4.1 on 2024-11-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0002_dayentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayEntryAsString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('last_transaction_price', models.CharField(blank=True, max_length=50, null=True)),
                ('max_price', models.CharField(blank=True, max_length=50, null=True)),
                ('min_price', models.CharField(blank=True, max_length=50, null=True)),
                ('avg_price', models.CharField(blank=True, max_length=50, null=True)),
                ('percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('profit', models.CharField(blank=True, max_length=50, null=True)),
                ('total_profit', models.CharField(blank=True, max_length=50, null=True)),
                ('company_code', models.CharField(max_length=50)),
            ],
        ),
    ]
