# Generated by Django 5.1.3 on 2024-12-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0008_alter_company_options_rename_name_company_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='code',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='max_sentiment_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='max_sentiment_value',
        ),
    ]
